"""Bompay — Blog routes."""
import os, uuid, secrets, logging, time, json, asyncio, hashlib, re
from datetime import datetime, timezone, timedelta
from typing import Optional, List
from pathlib import Path
from bson import ObjectId
import bcrypt
import jwt as pyjwt
import httpx
import requests as _requests
from fastapi import APIRouter, HTTPException, Request, Response, BackgroundTasks, UploadFile, File, Form
from fastapi.responses import JSONResponse, StreamingResponse
import csv, io
from fpdf import FPDF

from database import db
from core import (  # noqa: F401,F403,F405
    # auth
    hash_password, verify_password, hash_pin, verify_pin_hash,
    create_access_token, create_refresh_token, get_current_user, get_admin_user,
    set_auth_cookies, log_login_session,
    # wallet / ledger
    gen_account_number, get_wallet, ledger_entry,
    # notifications
    notify, audit, send_event_sms, send_event_email, send_event_notification, send_email,
    send_push_notification,
    # fraud
    fraud_check, fraud_check_user, auto_block_user,
    # providers
    call_sh, mock_sh, call_cdh, call_pg,
    get_vas_provider, get_service_provider, get_sms_config,
    get_sms_provider, get_sendora_api_key, get_sendora_sender_id, get_bulksms_credentials,
    # private helpers (explicitly imported)
    _cloudinary_upload, _cloudinary_delete, _email_html,
    _send_tier_approval_email, _send_tier_revoke_email,
    _send_via_sendora, _send_via_bulksms,
    _get_client_ip, _parse_ua,
)
from core import (  # noqa: F401,F403,F405
    # constants
    JWT_SECRET, JWT_ALGORITHM, ADMIN_EMAIL, ADMIN_PASSWORD,
    FRONTEND_URL, WEBHOOK_CRON_SECRET, SAFEHAVEN_BASE_URL, SAFEHAVEN_OWN_BANK_CODE,
    CDH_BASE_URL, PAIRGATE_BASE_URL,
    PG_DISCO_SLUGS, PG_BET_SLUGS,
    CDH_AIRTIME_NETWORK_IDS, CDH_ELECTRICITY_DISCO_IDS, CDH_DATA_PLANS, CDH_CABLE_PLANS,
    NIGERIAN_BANKS, MOCK_NAMES, CHARGE_CATEGORIES,
    WEBAUTHN_RP_ID, WEBAUTHN_ORIGIN, WEBAUTHN_RP_NAME,
    APP_NAME, EMERGENT_LLM_KEY,
    # webauthn
    generate_registration_options, verify_registration_response,
    generate_authentication_options, verify_authentication_response,
    base64url_to_bytes, options_to_json,
    AuthenticatorSelectionCriteria, UserVerificationRequirement,
    ResidentKeyRequirement, AttestationConveyancePreference,
    AuthenticatorAttachment, PublicKeyCredentialDescriptor,
    AuthenticatorAttestationResponse, RegistrationCredential,
    AuthenticatorAssertionResponse, AuthenticationCredential,
    cloudinary,
)
from models import *  # noqa: F401,F403,F405
import ledger as pg_ledger

router = APIRouter()
logger = logging.getLogger(__name__)

BLOG_SEED = [
  {"blog_id":"blog_01","slug":"digital-ajo-digitising-nigeria-savings","title":"The Rise of Digital Ajo: How BOMPAY is Digitising Nigeria's Most Popular Savings Tradition","excerpt":"For centuries, Nigerian communities have used Ajo to pool resources. In 2026, BOMPAY brings this tradition into the digital age with automated collections and bank-level security.","body":"<p>The concept of Ajo — also known as Esusu, Cha Cha, or Adashe depending on the region — is as old as Nigerian community itself. Every week or month, a trusted group of friends, market traders, or colleagues would pool a fixed amount of money, and one member would receive the whole pot on a rotating basis. No paperwork. No interest. Just trust.</p><p>For decades, this system thrived — until it started breaking down. Members moved to different cities. Coordinators absconded with funds. There was no way to dispute a missed contribution. BOMPAY set out to fix this.</p><p>Our digital Ajo feature launched in 2023 and has since become our most-used product. Over 150,000 active Ajo groups save a combined ₦12 billion every single month on our platform. Contributions are automatically deducted from wallets on due dates, missed payments are flagged in real time, and payouts happen in seconds — not days.</p><p>The transparency alone has changed communities. Members can see every contribution and every payout. There are no disputes because there is nothing to dispute about — the ledger is always open. Trust, it turns out, scales extremely well when it's backed by software.</p><p>Beyond the mechanics, what we've preserved is the spirit: the warmth of rotating savings, the celebration when it's your turn to receive, the sense of collective progress. BOMPAY didn't replace Ajo. We gave it a longer life.</p>","category":"Fintech Insights","tag":"Editor's Choice","author":"Adebayo Okonkwo","author_role":"CEO, BOMPAY","thumbnail_url":"https://images.unsplash.com/photo-1590650153855-d9e808231d41?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1590650153855-d9e808231d41?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"15 min","published":True,"created_at":"2026-02-01T09:00:00Z"},
  {"blog_id":"blog_02","slug":"build-wealth-nigeria-2026","title":"How to Build Wealth in Nigeria: A Practical Guide for 2026","excerpt":"Financial freedom isn't reserved for the wealthy. With the right tools and discipline, every Nigerian can build lasting wealth. Here's how.","body":"<p>Building wealth in Nigeria requires both mindset and mechanics. The mechanics have never been more accessible — digital wallets, instant transfers, automated savings, and micro-investment platforms have put tools once reserved for the wealthy into everyone's hands. The challenge is consistency.</p><p>Start with an emergency fund. Before investing or saving aggressively, build a buffer of 3–6 months of living expenses. Keep it in a high-yield savings product, not under a mattress. BOMPAY Ajo is perfect for this — set up a solo group, contribute automatically every month, and lock it until the target is reached.</p><p>Next, eliminate high-cost debt. Informal loans with weekly interest can destroy wealth faster than any market crash. Use BOMPAY's fee-free transfers to consolidate and pay down costly obligations before layering on savings.</p><p>Then invest systematically. Even ₦5,000 a month invested in diversified assets — indexed funds, agricultural bonds, real estate fractional shares — compounds significantly over 10–15 years. The key word is systematically: automate contributions so they happen before you can spend the money.</p><p>Finally, protect what you build. Insurance, legal documentation, and digital records are the invisible infrastructure of wealth. A single health emergency or property dispute can erase years of saving. Treat financial protection as seriously as wealth creation itself.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"8 min","published":True,"created_at":"2026-01-28T09:00:00Z"},
  {"blog_id":"blog_03","slug":"ajo-2-upgrade","title":"Introducing BOMPAY Ajo 2.0: Smarter Group Savings with Auto-Pilot","excerpt":"Our most-loved feature just got a massive upgrade. Dispute resolution, missed-payment handling, and payout notifications are now fully automated.","body":"<p>When we launched Ajo in 2023, we knew we were building something special. What we didn't anticipate was how diverse the use cases would become: women cooperatives, church savings clubs, university students, corporate salary groups. Each group had slightly different needs — and our version 1.0 wasn't meeting all of them.</p><p>Ajo 2.0 is the result of 18 months of listening. The biggest ask was conflict resolution. What happens when someone misses a contribution? Previously, the group coordinator had to manually chase members and update records. Now, a missed payment triggers an automatic grace period, then a gentle SMS reminder, then a temporary suspension — all configurable by the group creator.</p><p>We've also added secret voting for payout order disputes, split-contribution support (two people contributing into one slot), and mid-cycle member removal. Every change is recorded and timestamped in an immutable audit log that any member can export.</p><p>The result: 94% fewer group breakdowns in our beta cohort, and a 31% increase in groups completing their full cycle. Ajo 2.0 is live now for all BOMPAY users.</p>","category":"Product Updates","tag":"Product","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1531482615713-2afd69097998?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1531482615713-2afd69097998?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"5 min","published":True,"created_at":"2026-01-22T09:00:00Z"},
  {"blog_id":"blog_04","slug":"mrs-adeyemi-epos-success","title":"How Mrs Adeyemi Tripled Her Market Revenue Using BOMPAY ePOS","excerpt":"A Lagos market trader went from ₦180K to ₦520K monthly revenue in 4 months. This is her story.","body":"<p>Mrs Grace Adeyemi has sold fabric in Balogun Market, Lagos, for twenty-one years. Her stall is small — barely four metres wide — but her reputation for quality Ankara and Aso-oke is immense. Yet until eight months ago, she was losing customers every week for one reason: she didn't accept card payments.</p><p>\"They come, they look, they say they don't have cash. I tell them there is an ATM down the road. By the time they walk back, they don't come back,\" she told us during a visit to her stall. \"I was losing maybe ₦50,000 every week to that ATM walk.\"</p><p>When a BOMPAY field agent approached her with our ePOS terminal in October 2025, she was sceptical. \"I thought it was going to be complicated. But she set it up in twenty minutes and I started accepting payments the same day.\"</p><p>In the four months since, her monthly revenue has grown from ₦180,000 to ₦520,000. She now also sells to wholesale buyers who transfer directly from their business accounts. \"My Ajo group is the same — I just contribute from the ePOS balance now.\"</p><p>Mrs Adeyemi is one of 120,000 merchants who have activated BOMPAY ePOS terminals in Nigerian markets, shopping malls, and roadside businesses. Their stories are the reason we built this product.</p>","category":"Merchant Stories","tag":"Success Story","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2026-01-15T09:00:00Z"},
  {"blog_id":"blog_05","slug":"cashless-nigeria-2026","title":"Nigeria's Cashless Revolution: Where Are We in 2026?","excerpt":"CBN's cashless policy is bearing fruit. We analysed 50 million transactions to understand how Nigerians are paying in 2026.","body":"<p>In 2012, when the Central Bank of Nigeria announced the cashless policy for Lagos, the reaction was sceptical. ATMs were unreliable, POS terminals were scarce, and mobile internet was patchy. Fourteen years later, Nigeria is quietly becoming one of the most dynamic cashless economies in Africa.</p><p>The data tells the story. BOMPAY processed 50 million transactions in the last twelve months. Of those, 67% were peer-to-peer transfers, 21% were bill payments, 8% were merchant ePOS transactions, and 4% were other services. Two years ago, ePOS was under 2% of our transaction mix. The shift is real and accelerating.</p><p>What changed? Three things: smartphone penetration now exceeds 60% among adults; mobile data costs have dropped 40% since 2022; and a generation of Nigerians grew up with Flutterwave, Paystack, and BOMPAY — they simply don't relate to cash the same way their parents did.</p><p>Challenges remain. Rural access is uneven. Fintech fraud losses hit ₦52 billion in 2025, a number that erodes user trust. And merchant adoption is concentrated in urban centres. But the direction is unmistakable. Cashless Nigeria is no longer a policy goal — it's an emerging reality.</p>","category":"Fintech Insights","tag":"Industry","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1563013544-824ae1b704d3?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1563013544-824ae1b704d3?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"12 min","published":True,"created_at":"2026-01-10T09:00:00Z"},
  {"blog_id":"blog_06","slug":"ajo-vs-bank-savings-investment","title":"Ajo vs Bank Savings vs Investment: Which Is Right for You?","excerpt":"Three very different ways to save money, three very different outcomes. We break down the maths so you can decide.","body":"<p>Every savings vehicle has a personality. Understanding that personality — the risk profile, the liquidity constraints, the psychological mechanisms — is the first step to choosing the right one for your situation.</p><p>Bank savings accounts are the safest and most liquid, but their effective returns after inflation are often negative. A 2.5% annual interest rate on a savings account when inflation runs at 22% means you are losing purchasing power every year you leave money there. Use them for short-term parking, not wealth building.</p><p>Ajo (rotating savings) has a different psychology: it forces regular contributions, creates social accountability, and delivers a lump sum at your turn. The 'return' is not financial — it's the lump-sum access you couldn't have saved alone. Best for: large one-time expenses (school fees, equipment, travel) you couldn't otherwise accumulate.</p><p>Investment — whether in stocks, mutual funds, treasury bills, or real estate — is where long-term wealth is built. The compounding effect over 10–20 years dwarfs both savings accounts and Ajo in terms of wealth creation. The tradeoff is time horizon and risk tolerance.</p><p>The right answer is almost always all three, in proportion to your income stage: emergency buffer in savings, medium-term goals in Ajo, long-term wealth in diversified investments.</p>","category":"Financial Literacy","tag":"Savings","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2025-12-30T09:00:00Z"},
  {"blog_id":"blog_07","slug":"bompay-500k-users","title":"BOMPAY Crosses 500,000 Active Users — Our Journey and What's Next","excerpt":"It started with a frustration: sending money in Nigeria was too hard. Half a million users later, we're just getting started.","body":"<p>We didn't set out to reach 500,000 users. We set out to solve one problem: sending money between Nigerian banks took too long and cost too much. Every Nigerian knew the frustration of failed transfers, high fees, and 24-hour delays. We thought we could do better.</p><p>The first 1,000 users came through our own social circles in Lagos and Abuja. The next 10,000 came through word of mouth — referrals from people who were genuinely delighted that transfers worked. At BOMPAY, we never paid for our first million naira of transactions. Every one of them came because someone told a friend.</p><p>The jump from 10,000 to 100,000 happened when we launched Ajo. Suddenly, BOMPAY wasn't just a transfer app — it was a community platform. Groups formed, cycles completed, and members brought in new members. Our growth rate doubled in the month after launch.</p><p>At 500,000, we're proud but not satisfied. Our next chapter involves merchant payments, credit products, international remittances, and eventually, a full banking licence. The infrastructure we've built for transfers and savings will power all of it. Thank you for being part of this.</p>","category":"Company News","tag":"Milestone","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"4 min","published":True,"created_at":"2025-12-20T09:00:00Z"},
  {"blog_id":"blog_08","slug":"understanding-nibss-instant-transfers","title":"Understanding NIBSS: Why Nigerian Bank Transfers Work the Way They Do","excerpt":"Every time you send money to another Nigerian bank, NIBSS is involved. Here's the infrastructure powering Nigeria's payment rails — explained simply.","body":"<p>NIBSS — the Nigeria Inter-Bank Settlement System — is the invisible backbone of Nigerian banking. Founded in 1993, it is owned equally by all Nigerian banks and the Central Bank of Nigeria, and it processes virtually every interbank payment made in the country.</p><p>When you initiate a transfer from BOMPAY to a GTBank account, your instruction travels to NIBSS, which validates the recipient's account, checks for fraud signals, deducts from your bank's settlement account, and credits the recipient's bank — all within seconds. This process, called NIP (NIBSS Instant Payment), handles over 8 million transactions daily.</p><p>Before NIP, transfers could take 24 hours through the RTGS (Real Time Gross Settlement) system. The launch of NIP in 2011 changed Nigerian banking permanently. It is one of Africa's most sophisticated real-time payment infrastructures.</p><p>Understanding this helps explain why transfers occasionally fail: the failure is usually not on BOMPAY's side, but a NIBSS validation error, a recipient bank's system downtime, or an incorrect account number. When BOMPAY shows 'Transfer Pending,' NIBSS is processing — and in almost every case, it resolves within minutes.</p>","category":"Fintech Insights","tag":"Education","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1518770660439-4636190af475?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1518770660439-4636190af475?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"9 min","published":True,"created_at":"2025-12-15T09:00:00Z"},
  {"blog_id":"blog_09","slug":"epos-for-small-businesses","title":"5 Reasons Every Small Nigerian Business Needs an ePOS Terminal in 2026","excerpt":"Cash-only is a competitive disadvantage. Here's why accepting card payments is no longer optional for Nigerian traders and shop owners.","body":"<p>We surveyed 2,000 Nigerian small business owners in Q4 2025. The number one reason customers walked away without buying was not price or product — it was payment friction. Forty-three percent of respondents reported losing a customer in the past week because they didn't have cash.</p><p>1. You capture impulse purchases. Cards and mobile payments remove the 'I'll come back when I have cash' excuse. Research shows impulse purchases increase 28% when card payment is available at point of sale.</p><p>2. You access formal financial records. Every ePOS transaction creates a digital record usable as evidence of income for bank loans, government grants, and supplier credit. Cash businesses are invisible to the formal financial system.</p><p>3. You reduce cash-handling risk. Cash in a till is a theft risk. Cash transactions are prone to counterfeit notes. Digital payments eliminate both overnight.</p><p>4. You join the loyalty ecosystem. BOMPAY ePOS merchants automatically get listed in our merchant directory, gaining visibility to 500,000+ BOMPAY users searching for local businesses.</p><p>5. The cost is minimal. BOMPAY ePOS charges 1.5% per transaction, capped at ₦2,000. On a ₦500,000 revenue month, that's ₦7,500 — less than the cost of a single bank withdrawal fee per day. The ROI from captured sales far exceeds the fee.</p>","category":"Merchant Stories","tag":"Business","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1589758438368-0ad531db3366?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1589758438368-0ad531db3366?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-12-10T09:00:00Z"},
  {"blog_id":"blog_10","slug":"virtual-card-online-shopping-nigeria","title":"How to Shop Safely Online from Nigeria Using a Virtual Card","excerpt":"Online shopping fraud costs Nigerians billions every year. A virtual card limits your exposure without limiting your ability to buy from global stores.","body":"<p>Online shopping fraud is the fastest-growing financial crime in Nigeria. In 2025, the Economic and Financial Crimes Commission reported losses of ₦28 billion from e-commerce fraud — a 67% increase from 2023. The primary vector: compromised card details from insecure checkout pages.</p><p>A virtual card solves this by creating a disposable card number linked to your wallet. You fund it with exactly the amount you need for a purchase, use it once, and the remaining balance returns to your wallet. Even if the merchant's database is breached, your card details are worthless — the number is already spent.</p><p>BOMPAY Virtual Card works with all major international platforms: Amazon, Alibaba, AliExpress, Shein, Netflix, Spotify, Apple, Google Play. The card is denominated in NGN but processes in USD at competitive exchange rates.</p><p>For recurring subscriptions, we recommend using a separate virtual card per service, funded with exactly the subscription amount each cycle. If the card is ever compromised, simply freeze it and issue a new one in seconds — without touching your main wallet balance.</p><p>Safety isn't about avoiding the internet. It's about using the right tools to shop with confidence.</p>","category":"Financial Literacy","tag":"Security","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2025-12-05T09:00:00Z"},
  {"blog_id":"blog_11","slug":"naira-devaluation-protect-savings","title":"How to Protect Your Savings from Naira Devaluation","excerpt":"The naira has lost 40% of its value since 2023. Here are practical strategies Nigerians are using to preserve purchasing power.","body":"<p>Currency devaluation is an uncomfortable reality for Nigerian savers. Since the FX unification policy of 2023, the naira has experienced significant volatility. For people whose savings are entirely in naira, this represents a real and ongoing erosion of purchasing power.</p><p>The most effective hedge is diversification. This doesn't require a foreign bank account or sophisticated financial knowledge — it requires spreading your savings across assets with different inflation sensitivities.</p><p>Dollar-denominated assets are the most direct hedge. Dollar savings accounts, USD-linked money market funds, and foreign exchange holdings all appreciate in naira terms as the currency weakens. BOMPAY's partner institutions offer USD wallet capabilities for qualifying users.</p><p>Real assets — land, physical gold, and commodities — have historically maintained value through inflationary periods. Nigerian agricultural land, in particular, has appreciated faster than any other asset class in the past five years.</p><p>Business investment is another powerful hedge: a productive business generates revenue that grows with prices, unlike a fixed naira deposit that erodes in real terms. The risk is operational, but the upside is genuine inflation protection.</p><p>No single strategy is perfect. A combination of 40% naira savings (for liquidity), 40% dollar or real assets (for purchasing power protection), and 20% business/investment (for growth) provides both stability and long-term resilience.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1554224155-6726b3ff858f?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1554224155-6726b3ff858f?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"10 min","published":True,"created_at":"2025-11-28T09:00:00Z"},
  {"blog_id":"blog_12","slug":"bvn-explainer-nigeria","title":"BVN Explained: What It Is, Why It Matters, and How to Protect Yours","excerpt":"Your Bank Verification Number is the most important 11 digits in your financial life. Here's everything you need to know.","body":"<p>The Bank Verification Number (BVN) was introduced by the Central Bank of Nigeria in 2014 to reduce identity fraud in the banking sector. Before BVN, a single person could open dozens of bank accounts under different names — enabling mass fraud, money laundering, and loan defaults with impunity.</p><p>Your BVN is an 11-digit biometric identifier that links your fingerprints and facial recognition to every bank account you hold. When you open a new account, the bank verifies your BVN against the NIBSS biometric database — and if any detail doesn't match, the account is rejected.</p><p>Protecting your BVN is critical. Never share it with strangers, callers, or unverified apps. Banks, including BOMPAY, will never call you and ask for your BVN. If someone has your BVN, they can potentially open accounts in your name or impersonate you to lenders — treat it with the same confidentiality as your PIN.</p><p>If you suspect your BVN has been compromised, contact NIBSS directly through the official channels, place a temporary freeze on your banking profile, and report to EFCC. The process is bureaucratic but necessary.</p><p>At BOMPAY, BVN verification is one layer in a multi-factor identity system that also includes facial recognition, phone number verification, and device binding. We take the security of your financial identity seriously.</p>","category":"Financial Literacy","tag":"Security","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1573164574397-dd250bc8a598?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1573164574397-dd250bc8a598?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"8 min","published":True,"created_at":"2025-11-20T09:00:00Z"},
  {"blog_id":"blog_13","slug":"mr-ibrahim-kano-merchant","title":"How Malam Ibrahim's Spare Parts Shop in Kano Now Accepts Online Payments","excerpt":"From a northern market in Kano to reaching customers across Nigeria — a merchant story about digital transformation in an unexpected place.","body":"<p>Malam Ibrahim Suleiman has operated his engine spare parts shop in Kano's Yankaba Market for fifteen years. His customers are mechanics, fleet operators, and transport companies across the north — relationships built over years of trust and reliable supply.</p><p>But trust didn't pay his suppliers when they started demanding electronic transfers. And mechanics in Sokoto and Maiduguri couldn't physically come to Kano to buy parts. His business was geographically constrained in a way that disadvantaged him against Lagos-based competitors with better digital infrastructure.</p><p>\"My children set up BOMPAY for me,\" he tells us. \"Within a week, I was receiving transfers from Abuja, from Kaduna, from everywhere. One customer from Port Harcourt bought ₦480,000 worth of parts and transferred immediately. That would never have happened before.\"</p><p>Today, 35% of Malam Ibrahim's revenue comes from outside Kano state. He has set up an Ajo group with six other Yankaba merchants to collectively buy inventory at bulk prices — pooling capital to negotiate better terms from distributors.</p><p>His story represents the quiet revolution happening in Nigeria's informal economy. Digital payments aren't just a convenience — they're expanding markets and creating new commercial relationships that physical distance would have previously prevented.</p>","category":"Merchant Stories","tag":"Success Story","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1534939561126-855b8675edd7?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1534939561126-855b8675edd7?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"5 min","published":True,"created_at":"2025-11-15T09:00:00Z"},
  {"blog_id":"blog_14","slug":"bompay-kyc-tier-system","title":"BOMPAY's KYC Tier System: What Each Level Means for Your Account","excerpt":"Know Your Customer regulations protect you — but they can also limit your account. Here's how to unlock higher limits and what documentation you need.","body":"<p>Every Nigerian fintech operates under a tiered KYC (Know Your Customer) framework mandated by the Central Bank of Nigeria. The framework exists to prevent money laundering, terrorism financing, and fraud — but it also means different users have different account capabilities depending on their verification level.</p><p>Tier 1 (Basic): Requires only your BVN and phone number. Transaction limit: ₦50,000 single, ₦300,000 daily. Suitable for occasional, low-value transfers and bill payments.</p><p>Tier 2 (Verified): Requires BVN plus a government-issued ID (National ID, Voter's Card, or Driver's License). Limit: ₦200,000 single, ₦1,000,000 daily. Suitable for regular users and small business owners.</p><p>Tier 3 (Full): Requires BVN, government ID, and proof of address (utility bill or bank statement not older than 3 months). Limit: ₦1,000,000 single, ₦5,000,000 daily. For business owners and high-volume users.</p><p>At BOMPAY, KYC verification typically completes within 60 minutes during business hours. Our AI-powered document verification system accepts photos taken on any smartphone — no scanner required. Once verified, your limits update instantly without any downtime.</p><p>We strongly encourage all users to complete at least Tier 2 verification to access the full BOMPAY experience.</p>","category":"Product Updates","tag":"Product","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1573164574397-dd250bc8a598?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1573164574397-dd250bc8a598?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-11-10T09:00:00Z"},
  {"blog_id":"blog_15","slug":"fintech-fraud-prevention-nigeria","title":"Staying Safe from Fintech Fraud: A Guide for Every Nigerian","excerpt":"Social engineering, phishing, SIM swaps — fraud tactics are evolving. Here's exactly how to protect your BOMPAY account and your money.","body":"<p>Fintech fraud in Nigeria takes many forms, and the tactics evolve faster than public awareness. Understanding the common attack vectors is your first line of defence.</p><p>Social engineering is the most prevalent. A fraudster calls, pretending to be a bank or BOMPAY representative, and creates a sense of urgency — 'Your account will be frozen in 30 minutes unless you provide your OTP.' Remember: no legitimate financial institution will ever ask for your OTP, PIN, or password. Ever. Full stop.</p><p>SIM swap fraud occurs when a fraudster convinces your mobile network to transfer your phone number to a new SIM they control. With your number, they can reset passwords and intercept OTPs. Protect against this by setting a SIM swap PIN with your network provider and registering an alternate authentication method.</p><p>Phishing emails and fake apps mimic legitimate platforms to steal credentials. Always download BOMPAY only from the official App Store or Google Play, and verify the sender domain on any email claiming to be from BOMPAY.</p><p>At BOMPAY, we've implemented transaction PIN for every outgoing transfer, biometric authentication options, device binding, and real-time fraud scoring using machine learning. But no platform can fully replace user vigilance. Your awareness is the most powerful fraud prevention tool.</p>","category":"Financial Literacy","tag":"Security","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1550745165-9bc0b252726f?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1550745165-9bc0b252726f?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"9 min","published":True,"created_at":"2025-11-05T09:00:00Z"},
  {"blog_id":"blog_16","slug":"bompay-airtime-cashback","title":"How Our Cashback Programme Works: Earn While You Spend","excerpt":"Every airtime top-up, data bundle, and electricity payment earns you BOMPAY cashback. Here's the full breakdown of how the programme works.","body":"<p>At BOMPAY, we believe you should earn something back every time you use the platform. Our cashback programme rewards transacting users with a percentage of every VAS (Value Added Service) payment returned to their wallet.</p><p>Here's how the rates work: Airtime top-ups earn 1% cashback. Data bundles earn 1.5% cashback. Electricity token purchases earn 2% cashback. Cable TV subscriptions earn 1% cashback. These percentages are calculated on the transaction amount and credited to your wallet within 60 seconds of a successful transaction.</p><p>There are no minimum amounts, no registration required, and no points to redeem. The cashback is real money in your wallet, immediately available for transfers or further purchases.</p><p>For high-frequency users — those making 10+ VAS transactions per month — the cumulative cashback can be significant. A small business owner paying ₦50,000 per month in electricity across multiple locations earns ₦1,000 in cashback monthly — ₦12,000 per year — for doing nothing extra.</p><p>The programme is our way of saying thank you for choosing BOMPAY for your daily financial needs. We're committed to making every transaction more rewarding than the last.</p>","category":"Product Updates","tag":"Product","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"5 min","published":True,"created_at":"2025-10-30T09:00:00Z"},
  {"blog_id":"blog_17","slug":"school-fees-bompay","title":"School Fees Season: How Nigerian Parents Are Using BOMPAY to Pay Faster","excerpt":"September and January are the most financially stressful months for Nigerian parents. Here's how digital tools are easing the burden.","body":"<p>In Nigeria, school fees season is one of the most financially demanding periods for households. September (new academic year) and January (second term) often coincide with other financial pressures — rent payments, medical bills, and end-of-year obligations — creating a perfect storm of cash flow stress.</p><p>The traditional approach involved multiple bank visits, cash withdrawals, and manual payments. Many schools have now moved to electronic payment requirements, which has both improved efficiency and created new frustrations for families relying on legacy banking infrastructure.</p><p>BOMPAY users are navigating this differently. With instant bank transfers to any Nigerian account, parents can send fees directly from their wallet to school accounts in seconds, regardless of the bank. Several schools have partnered with BOMPAY to offer direct in-app fee payment portals that automatically mark student fees as paid in the school's system.</p><p>For parents managing fees for multiple children across different schools, our scheduled payment feature (available in BOMPAY Pro) allows fees to be queued in advance and automatically executed on the payment due date, avoiding late fees and the chaos of last-minute payments.</p><p>Financial stress doesn't disappear — but it becomes manageable. That's what BOMPAY is for.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1509062522246-3755977927d7?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-10-25T09:00:00Z"},
  {"blog_id":"blog_18","slug":"abuja-restaurant-epos","title":"From Street Food to Restaurant: Blessing's ePOS Journey in Abuja","excerpt":"Blessing started with a pot and a plastic table. Three years later, she runs a ₦8M restaurant and processes all payments through BOMPAY ePOS.","body":"<p>Blessing Okeke started selling jollof rice from the front of her house in Gwarinpa, Abuja, in 2020. Her initial capital was ₦15,000 — enough for ingredients, charcoal, and two large pots. Customers paid cash. Blessing counted every naira by hand at the end of each day.</p><p>\"I was nervous about ePOS at first,\" she admits now, seated in her 40-seat restaurant on Cadastral Zone B03. \"I thought customers would not trust it — they would think I was taking their card information. But they actually loved it. Corporate people especially — they never carry cash.\"</p><p>The transition from street food to a formal restaurant is rare in Nigeria, and Blessing credits three things: quality food, location, and financial infrastructure. \"Before BOMPAY, I was limited to customers who had cash on them. Now I get corporate lunch orders, catering bookings, and even international guests who pay with foreign cards through the terminal.\"</p><p>Her monthly revenue now exceeds ₦8 million. She employs twelve people full-time. Her BOMPAY business account provides the transaction history that enabled her first formal loan from a microfinance bank. And her Ajo group — five women who saved together during lockdown — recently pooled ₦2.4 million to invest in a shared generator for their neighbourhood.</p>","category":"Merchant Stories","tag":"Success Story","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2025-10-20T09:00:00Z"},
  {"blog_id":"blog_19","slug":"open-banking-nigeria","title":"Open Banking is Coming to Nigeria: What It Means for You","excerpt":"The CBN's open banking framework will fundamentally change how financial services are delivered in Nigeria. Here's what you need to know.","body":"<p>Open banking — the regulatory requirement that banks share customer data with authorised third parties via secure APIs — is transforming financial services globally. The Central Bank of Nigeria issued its open banking framework in 2023, and implementation is accelerating in 2026.</p><p>For consumers, open banking means three things. First, account aggregation: you'll be able to see all your bank accounts, investments, and loans in one place — including accounts at banks you don't primarily use. Second, better credit decisions: lenders will have richer data to assess your creditworthiness, potentially offering lower rates to people who've been shut out of formal credit. Third, competition: with data portability, it becomes easier to switch financial providers, forcing all institutions to improve their products.</p><p>For fintechs like BOMPAY, open banking is an opportunity to deepen our services. We can offer better budgeting tools, more personalised savings recommendations, and credit products tailored to real spending patterns rather than guesses.</p><p>The transition won't be seamless. Data privacy concerns are real, legacy banks will resist the loss of their data monopolies, and implementation will be uneven. But the direction is clear, and the benefits for Nigerian consumers and businesses are substantial.</p>","category":"Fintech Insights","tag":"Industry","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"11 min","published":True,"created_at":"2025-10-15T09:00:00Z"},
  {"blog_id":"blog_20","slug":"bompay-business-account-launch","title":"Introducing BOMPAY Business: Accounts Built for Nigerian Entrepreneurs","excerpt":"Sole traders, SMEs, and growing businesses now have a dedicated account tier with payroll tools, multi-user access, and business analytics.","body":"<p>When we surveyed our 500,000 users last year, 43% told us they also used BOMPAY for business transactions — even though we didn't have a formal business product. They were managing payroll through personal accounts, tracking expenses manually, and adding team members to their personal wallets as workarounds.</p><p>This wasn't sustainable. Personal accounts don't support multi-user access, don't generate the kind of transaction reports needed for tax compliance, and don't offer the cashflow tools businesses need to plan effectively.</p><p>BOMPAY Business changes this. Business accounts get a dedicated virtual account number for receiving customer payments, multi-user access with role-based permissions, automated monthly transaction statements formatted for accountants, payroll batch processing for up to 500 employees, and priority customer support.</p><p>For sole traders and micro businesses, the entry tier is free — same as our personal accounts. For growing businesses needing more sophisticated tools, our Pro and Enterprise tiers offer advanced analytics, custom payment links, and API access.</p><p>We built BOMPAY Business because Nigerian entrepreneurs deserve financial infrastructure as sophisticated as the businesses they're building. Available now. Free to open.</p>","category":"Product Updates","tag":"Product","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1551434678-e076c223a692?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1551434678-e076c223a692?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-10-10T09:00:00Z"},
  {"blog_id":"blog_21","slug":"nigeria-microfinance-landscape","title":"Nigeria's Microfinance Revolution: 1,000+ MFBs and What They Actually Do","excerpt":"Nigeria has over 1,000 licensed microfinance banks. Most Nigerians have never heard of most of them. Here's why they matter.","body":"<p>Nigeria has one of the largest microfinance banking sectors in Africa, with over 1,000 licensed Microfinance Banks (MFBs) operating across the country. Yet most Nigerians have never interacted with one directly — their products reach consumers through partnerships with fintechs like BOMPAY rather than through traditional branches.</p><p>BOMPAY operates on a microfinance banking licence issued by the CBN, which means we're subject to the same regulatory oversight as a traditional bank, but optimised for digital delivery. Our virtual accounts, savings products, and payment services are all regulated under this framework.</p><p>MFBs were originally designed to serve the unbanked and underbanked — people who couldn't meet the minimum balance requirements of commercial banks. In rural areas, they remain lifelines for small farmers, market traders, and artisans who need access to micro-credit and savings services.</p><p>The sector is consolidating. CBN's recapitalisation requirements have led many smaller MFBs to merge or surrender their licences. What's emerging is a tiered system: rural community MFBs serving local markets, and digital MFBs like BOMPAY serving the national urban and peri-urban market at scale. Both are essential. Neither alone is sufficient.</p>","category":"Fintech Insights","tag":"Industry","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"10 min","published":True,"created_at":"2025-10-05T09:00:00Z"},
  {"blog_id":"blog_22","slug":"transfer-fees-nigeria-comparison","title":"Transfer Fees in Nigeria: A Full Comparison Across All Major Platforms","excerpt":"We did the maths so you don't have to. Here's exactly what it costs to send money across the major Nigerian fintech and bank platforms in 2026.","body":"<p>Transfer fees are one of the most complained-about aspects of Nigerian banking — and rightfully so. A ₦50 stamp duty plus a ₦10–100 processing fee on every transfer adds up. For frequent senders, the annual cost can exceed ₦50,000.</p><p>We analysed fee structures across 12 platforms for five common transfer scenarios: ₦500 (airtime equivalent), ₦5,000 (typical market payment), ₦50,000 (rent contribution), ₦200,000 (salary payment), and ₦1,000,000 (business transfer).</p><p>The results confirmed what power users already know: fintechs are consistently cheaper than traditional banks for most transaction sizes. The CBN stamp duty of ₦50 applies to all transfers above ₦10,000 regardless of platform — this is regulatory and cannot be waived. What varies is the processing fee on top.</p><p>BOMPAY charges a flat ₦5 processing fee for intra-platform transfers (BOMPAY to BOMPAY) — with no stamp duty for amounts under ₦10,000. For interbank transfers, the standard CBN stamp duty applies plus a ₦50 processing fee. For the five scenarios above, BOMPAY's total cost was consistently in the lowest tier across all tested platforms.</p><p>Our commitment: transfer fees should never be a reason to not use BOMPAY. If you find a comparable platform offering lower fees for equivalent reliability, we want to know about it.</p>","category":"Fintech Insights","tag":"Personal Finance","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1543286386-713bdd548da4?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1543286386-713bdd548da4?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"8 min","published":True,"created_at":"2025-12-22T09:00:00Z"},
  {"blog_id":"blog_23","slug":"salary-day-financial-planning","title":"What to Do on Salary Day: A 10-Minute Financial Routine for Nigerian Workers","excerpt":"Most Nigerians receive a salary and watch it disappear within days. Here's the exact routine that changes that pattern.","body":"<p>The 'salary evaporation problem' is real and universal. You receive your credit alert, exhale with relief, and two weeks later you're wondering where it all went. The solution isn't earning more — it's a deliberate routine that runs in the first 10 minutes after every salary credit.</p><p>Step 1 (2 minutes): Transfer 10–20% to your Ajo group or savings wallet immediately. Before any expenses. Before any social media. This is the foundational habit of every financially stable person we've studied.</p><p>Step 2 (3 minutes): Pay fixed obligations — rent, utilities, subscriptions. Set these up as scheduled payments in BOMPAY so they execute automatically on salary day. Removing the decision removes the temptation to defer.</p><p>Step 3 (3 minutes): Review last month's variable spending from your transaction history. BOMPAY's spending summary shows categories automatically. Pick one area where you overspent and set a mental or written limit for the coming month.</p><p>Step 4 (2 minutes): Check your Ajo group's progress and any upcoming payout schedules. Knowing exactly where you stand creates a feedback loop that reinforces the saving habit.</p><p>The entire routine takes 10 minutes. The financial outcomes, compounded over years, can be transformative. The hardest part isn't the routine — it's starting it once.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1500382017468-9049fed747ef?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"5 min","published":True,"created_at":"2025-11-25T09:00:00Z"},
  {"blog_id":"blog_24","slug":"women-financial-inclusion-nigeria","title":"Women and Financial Inclusion: How BOMPAY Is Closing the Gender Gap","excerpt":"Women control 80% of household spending in Nigeria yet remain disproportionately excluded from formal financial services. We're changing that.","body":"<p>The statistics are stark. According to the EFInA Access to Financial Services survey, 38% of Nigerian women are financially excluded — compared to 24% of men. Women are less likely to have a bank account, less likely to have received a formal loan, and less likely to have any investment assets.</p><p>The barriers aren't attitudinal — Nigerian women are among the most entrepreneurial in the world, running approximately 41% of all SMEs. The barriers are structural: identity documentation requirements that exclude women who never registered a birth certificate, physical branch locations that are unsafe to visit alone, and credit scoring models that penalise informal income patterns.</p><p>BOMPAY has addressed these barriers through product design rather than marketing. Our BVN-based onboarding accepts a wider range of identity documents including voter's cards and NIN — documents Nigerian women are more likely to have than passports or driver's licences. Our Ajo feature formally digitises savings structures that women already use informally. And our credit scoring for the upcoming loan product uses transaction history rather than traditional employment records.</p><p>Progress is measurable: 57% of our Ajo groups are led by women. Women account for 48% of our active user base, above the sector average of 35%. We have more work to do, but the direction is right.</p>","category":"Company News","tag":"Inclusion","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"9 min","published":True,"created_at":"2025-11-12T09:00:00Z"},
  {"blog_id":"blog_25","slug":"bompay-api-launch","title":"BOMPAY API: Now Available for Developers and Businesses","excerpt":"Build on BOMPAY's payment infrastructure. Our RESTful API enables any business to add instant payments, virtual accounts, and wallet services to their product.","body":"<p>For the past year, we've had an informal API used by a handful of enterprise partners. Today, we're opening it to all registered businesses as a public beta.</p><p>The BOMPAY API provides four primary capabilities. First, virtual account provisioning: create dedicated BOMPAY virtual accounts for your customers or business units, enabling real-time payment identification without reconciliation friction. Second, outbound transfers: send money to any Nigerian bank account programmatically, ideal for payroll, vendor payments, and disbursements. Third, bill payments: pay airtime, data, electricity, and cable TV for your customers at wholesale rates with a simple POST request. Fourth, webhooks: receive real-time transaction notifications so your platform stays in sync with BOMPAY's ledger.</p><p>Authentication uses industry-standard OAuth 2.0 with API keys and webhook signatures for security. Rate limits start at 100 requests per minute for sandbox and 1,000 per minute for production.</p><p>The documentation is available at developers.bompay.app. We're offering the first three months free for startups — no transaction fees, no API fees. After that, pricing is based on transaction volume with generous tier thresholds. We'd rather have 1,000 developers building on our infrastructure than 10 enterprise deals.</p>","category":"Product Updates","tag":"Developer","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1518770660439-4636190af475?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1518770660439-4636190af475?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2026-01-05T09:00:00Z"},
  {"blog_id":"blog_26","slug":"new-year-financial-goals-2026","title":"7 Financial Goals to Set for 2026 (and How to Actually Achieve Them)","excerpt":"New Year resolutions fail because they're abstract. These seven goals are specific, measurable, and achievable with tools you already have.","body":"<p>The difference between financial resolutions that stick and those that fade by February is specificity. 'Save more money' is a wish. 'Contribute ₦20,000 to my Ajo group every 15th of the month starting January' is a plan.</p><p>Goal 1: Build a ₦500,000 emergency fund by December 2026. Break it down: ₦41,700 per month. Set up automated savings in BOMPAY to deduct this every salary day before you see the balance.</p><p>Goal 2: Clear your highest-interest debt by March. List all debts, identify the one with the highest interest rate, and direct every spare naira at it until it's gone. The psychological lift of eliminating a debt accelerates the next one.</p><p>Goal 3: Start investing — even ₦5,000 per month. Choose a platform, choose an asset class (money market funds are the safest starting point), and make the first investment this week, not next month.</p><p>Goal 4: Protect your income with health insurance. HMO plans for individuals start at ₦45,000 per year in Nigeria. At ₦3,750 per month, this is one of the highest-ROI financial decisions most uninsured Nigerians can make.</p><p>Goal 5: Reduce transfer fees by consolidating payments on one platform. Using three apps for transfers, bill payments, and savings means paying fees three times for similar services.</p><p>Goal 6: Learn one new financial concept each month. 12 months, 12 concepts. Start with 'compound interest.' Everything else flows from that.</p><p>Goal 7: Review your financial position quarterly. A 30-minute review every three months — comparing savings, expenses, and investment returns against your goals — is worth more than any financial advice article.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"10 min","published":True,"created_at":"2026-01-01T09:00:00Z"},
  {"blog_id":"blog_27","slug":"port-harcourt-trader-expansion","title":"Agnes's BOMPAY Journey: From Port Harcourt Market to Pan-Nigeria Supplier","excerpt":"How a frozen fish trader expanded from a single market stall to supplying restaurants across five Nigerian states using BOMPAY.","body":"<p>Agnes Nwankwo started selling frozen fish in Mile 1 Market, Port Harcourt, in 2017. For the first three years, every transaction was cash — suppliers demanded cash, customers paid cash, and Agnes stored her daily earnings under a pile of clothes in her bedroom.</p><p>\"I was afraid of banks,\" she tells us plainly. \"Long queues, too many charges, they treat market people like we are not serious customers.\" She opened a BOMPAY account in 2023 on the recommendation of another trader who had already stopped carrying cash.</p><p>The transition was gradual. She started receiving transfers for small orders. Then she began paying suppliers electronically — which gave her a transaction record that reduced disputes. Then she started an Ajo group with twelve fish traders to buy bulk cold storage equipment. The group pooled ₦2.4 million in eight months and purchased a shared industrial freezer.</p><p>Today, Agnes supplies frozen fish to restaurants and caterers across Port Harcourt, Warri, Asaba, Onitsha, and Owerri. Payments come in via transfer. She has six employees. Her BOMPAY business account generates the financial statements she used to access a ₦3.5 million microfinance loan to buy a refrigerated vehicle.</p><p>\"BOMPAY didn't grow my business. I grew my business. But BOMPAY made it possible to grow at that speed,\" she says.</p>","category":"Merchant Stories","tag":"Success Story","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1556909211-36987daf7b4d?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1556909211-36987daf7b4d?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-12-08T09:00:00Z"},
  {"blog_id":"blog_28","slug":"fintech-regulation-cbn-2026","title":"What the CBN's 2026 Fintech Regulation Changes Mean for Your Money","excerpt":"The Central Bank of Nigeria issued sweeping new fintech guidelines in Q1 2026. Here's a plain-English explanation of what changed and what it means for users.","body":"<p>Regulatory changes in the fintech sector often feel abstract until they directly affect your account. The CBN's January 2026 circular on Digital Financial Services introduced several changes that BOMPAY users should understand.</p><p>Transaction monitoring thresholds have changed. Single transactions above ₦500,000 and aggregate daily transactions above ₦1,500,000 now trigger automatic enhanced due diligence review. For users regularly transacting at these levels, this may mean occasional requests for transaction documentation — this is a regulatory requirement, not a BOMPAY policy.</p><p>Virtual account rules have tightened. All virtual accounts must now be directly linked to a verified BVN and government-issued ID within 30 days of opening, or they will be restricted to receiving-only mode. BOMPAY completed this migration automatically for all users — if your account is restricted, it means your KYC is incomplete.</p><p>Consumer protection requirements have expanded. Fintechs must now respond to formal complaints within 48 hours (down from 72), maintain a minimum liquid reserve ratio, and publish quarterly transparency reports. BOMPAY already exceeded these standards. Our formal complaint resolution averages 4 hours.</p><p>The overall direction of these regulations is positive: they increase accountability across the sector, protect consumers, and establish clearer rules that reduce uncertainty for compliant operators like BOMPAY.</p>","category":"Fintech Insights","tag":"Regulation","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"9 min","published":True,"created_at":"2026-01-18T09:00:00Z"},
  {"blog_id":"blog_29","slug":"electricity-token-guide","title":"Understanding Your Electricity Token: What the Numbers Mean","excerpt":"Every prepaid electricity token is a 20-digit code that contains encoded information about your meter, units purchased, and tariff. Here's how to read it.","body":"<p>When you purchase prepaid electricity through BOMPAY, you receive a 20-digit token. Most people simply enter this number into their meter and move on — but understanding what's encoded in those 20 digits can help you verify purchases, dispute errors, and understand your energy consumption.</p><p>The 20-digit token is generated using the Standard Transfer Specification (STS), an international standard for prepaid electricity vending. The token contains encrypted information including your meter serial number, the number of kilowatt-hours (kWh) purchased, and a cryptographic hash that the meter uses to verify authenticity.</p><p>Different DisCos (Distribution Companies) in Nigeria use different tariff bands, which is why the same ₦1,000 purchase produces different unit quantities depending on your location. Lagos EKEDC users on Band A receive more units than Aba Power users on Band E, reflecting different tariff structures.</p><p>When your token doesn't load, the most common causes are: entering the digits incorrectly (the meter is case-sensitive), the token has already been used, or the token was generated for a different meter serial number. BOMPAY customer support can regenerate tokens for all purchases made on our platform, provided the original purchase was successful on our end.</p><p>Keep a screenshot of every electricity token purchase — it's your receipt and your evidence in any dispute.</p>","category":"Financial Literacy","tag":"Utilities","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2025-12-03T09:00:00Z"},
  {"blog_id":"blog_30","slug":"bompay-passkey-biometric-login","title":"BOMPAY Now Supports Passkeys: Log In Without Passwords, Ever Again","excerpt":"We've deployed WebAuthn passkey authentication. Here's how to enable it and why it's dramatically more secure than any password.","body":"<p>Passwords are the weakest link in any security chain. They get reused, forgotten, phished, and breached. Passkeys replace passwords entirely with cryptographic authentication tied to your physical device and biometrics — no password to remember, no password to steal.</p><p>BOMPAY's passkey implementation uses the W3C WebAuthn standard, the same technology used by Apple, Google, and Microsoft for passwordless authentication. When you enrol a passkey, your device generates a unique cryptographic key pair. The private key never leaves your device — it's secured by your fingerprint, face, or device PIN. BOMPAY stores only the public key, which is useless without the corresponding private key on your device.</p><p>The practical result: even if BOMPAY's servers were breached and our user database was stolen, attackers could not use those credentials to log in to your account. There is no password to breach. The private key is on your device, protected by biometrics.</p><p>To enable passkeys on BOMPAY: navigate to Settings > Security > Passkey, tap Enrol, and follow the device prompts. The process takes under 30 seconds. You can enrol multiple devices — your phone and tablet, for example — and manage them individually from the security settings page.</p><p>Passkeys are the future of authentication. We're proud to be one of the first Nigerian fintechs to offer them to our users.</p>","category":"Product Updates","tag":"Security","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1510511233900-1982d92bd835?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1510511233900-1982d92bd835?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-11-30T09:00:00Z"},
  {"blog_id":"blog_31","slug":"african-remittance-nigeria","title":"Receiving Money from the Diaspora: A Complete Guide to International Remittances","excerpt":"Over $20 billion flows from the Nigerian diaspora annually. Here's the cheapest, fastest, and safest way to receive it in 2026.","body":"<p>Nigeria is Africa's largest remittance recipient, receiving over $20 billion annually from Nigerians in the UK, US, Canada, Europe, and the rest of the world. For millions of families, these inflows are not supplemental income — they're the primary financial lifeline.</p><p>The remittance corridor has been plagued by high fees and unpredictable exchange rates. Traditional wire transfers through banks can charge 5–8% in fees and offer rates significantly below market. Money transfer operators like Western Union and MoneyGram are better but still expensive at 3–5%.</p><p>Digital remittance platforms have disrupted this. Services like Lemfi, Grey, and WorldRemit offer rates at 1–2% with near-market exchange rates, and transfers that complete in minutes rather than days. The key is choosing a platform that settles directly to a Nigerian bank account rather than routing through multiple correspondent banks.</p><p>For BOMPAY users receiving remittances: your BOMPAY virtual account number is a valid Nigerian bank account that can receive direct bank transfers. Some international platforms can settle directly to BOMPAY virtual accounts at interbank exchange rates.</p><p>When receiving large remittances (above $5,000 equivalent), ensure you understand the Form A/M documentation requirements to avoid CBN compliance flags. Your recipient bank or fintech should guide you through this — if they don't, that's a red flag about their compliance posture.</p>","category":"Financial Literacy","tag":"Remittance","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"11 min","published":True,"created_at":"2025-11-08T09:00:00Z"},
  {"blog_id":"blog_32","slug":"micro-credit-nigeria-sme","title":"Access to Credit: Why 70% of Nigerian SMEs Can't Get a Loan (and What We're Doing About It)","excerpt":"The credit gap for Nigerian SMEs is estimated at ₦617 billion. We're building the infrastructure to close it — starting with transaction-based lending.","body":"<p>The Central Bank of Nigeria estimates that 70% of Nigerian small and medium enterprises cannot access formal credit. The reasons are well-documented: insufficient collateral, lack of formal financial records, volatile income patterns, and risk-averse lending cultures at traditional banks.</p><p>The irony is that these businesses are often creditworthy — they just can't prove it through the documentation that traditional credit models require. A market trader who has been operating profitably for ten years has no way to demonstrate that track record to a bank loan officer who has never visited a market.</p><p>Transaction-based lending changes this equation. By analysing 12–24 months of verified transaction history — revenue patterns, expense consistency, savings behaviour — it's possible to build a credit profile that accurately predicts repayment behaviour without requiring collateral or formal payslips.</p><p>BOMPAY Loans (launching in Q2 2026) will use exactly this approach. Users who have maintained active BOMPAY accounts for more than 6 months will become eligible for initial loan offers based on their transaction history, starting at ₦50,000 and scaling with demonstrated financial behaviour. No guarantors. No collateral. No site visits.</p><p>We're not trying to solve the entire credit gap ourselves. But for our 500,000 users, we can provide a meaningful starting point.</p>","category":"Fintech Insights","tag":"Credit","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1560518883-ce09059eeffa?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1560518883-ce09059eeffa?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"10 min","published":True,"created_at":"2025-10-28T09:00:00Z"},
  {"blog_id":"blog_33","slug":"data-bundle-buying-guide","title":"Data Bundle Buying Guide: Stop Wasting Money on the Wrong Plan","excerpt":"Nigerians overpay by an estimated ₦15 billion annually on data bundles. Here's how to calculate the right plan for your actual usage.","body":"<p>Data bundle decisions are made emotionally, not analytically. We buy the plan that feels affordable in the moment, not the plan that's actually optimal for our usage pattern. The result is a pattern of buying too little (data exhaustion mid-month) or too much (unused data that expires).</p><p>The first step is measurement. Spend one month tracking your actual daily data consumption. Most Android phones have built-in data tracking under Settings > Network. iPhone users can find it under Settings > Mobile Data. The goal is to know your monthly gigabyte requirement — not guess it.</p><p>Most Nigerian mobile users consume between 3–8GB per month under normal usage. Heavy streamers and remote workers may consume 15–30GB. Armed with your actual number, compare bundle prices per gigabyte across MTN, Airtel, Glo, and 9Mobile — the per-GB price varies by up to 40% across plans and networks for the same monthly allowance.</p><p>BOMPAY's data purchase feature supports all four major networks, with pricing updated daily to reflect current promotions. We've added a 'best value' indicator that highlights the lowest per-GB rate available on your network at the time of purchase.</p><p>One often-overlooked tip: night data plans on MTN and Airtel offer 2–5x more data for the same price, valid between midnight and 5am. For downloading large files, streaming content for offline use, or running overnight updates, these represent exceptional value.</p>","category":"Financial Literacy","tag":"Personal Finance","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2025-10-22T09:00:00Z"},
  {"blog_id":"blog_34","slug":"bompay-charity-financial-literacy-tour","title":"BOMPAY's Financial Literacy Tour: 10,000 Nigerians Taught, 6 States, 4 Months","excerpt":"Our community team completed the largest financial literacy tour in BOMPAY's history. Here's what we taught — and what we learned.","body":"<p>In the four months between October 2025 and January 2026, BOMPAY's community and impact team ran financial literacy workshops in six Nigerian states: Lagos, Kano, Abuja FCT, Enugu, Kaduna, and Rivers. The goal was simple: reach Nigerians who are financially excluded not by choice but by lack of access to basic financial knowledge.</p><p>The workshops covered five topics: how to open and use a digital wallet; how to send money safely; how to start and manage an Ajo group; how to protect your account from fraud; and how to make a basic household budget. Sessions were conducted in English, Yoruba, Hausa, and Igbo, with participants ranging in age from 18 to 74.</p><p>What we taught was educational. What we learned was humbling. In Kano, we met a group of women who had been running an informal Ajo for 15 years with perfect compliance records — teaching us a thing or two about community trust infrastructure that we've now incorporated into Ajo 2.0. In Enugu, a retired teacher who had never used a smartphone learned to make a bank transfer in less than five minutes. In Port Harcourt, a 22-year-old became so enthused about virtual cards that she started her own informal tutorial group before the workshop was over.</p><p>10,046 Nigerians attended our workshops. 7,831 opened BOMPAY accounts. 3,400 started Ajo groups within 30 days. Numbers that represent real financial lives changed. We'll be back in 2026 with 12 states.</p>","category":"Company News","tag":"Community","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"8 min","published":True,"created_at":"2026-02-05T09:00:00Z"},
  {"blog_id":"blog_35","slug":"night-market-epos","title":"Night Markets Are Going Cashless: The Quiet Revolution in Lagos's After-Dark Economy","excerpt":"Lagos's famous night markets are embracing ePOS terminals. What's driving the shift — and what it means for the city's nighttime economy.","body":"<p>Walk through Lekki Phase 1 night market at 10pm on a Saturday, and you'll notice something different from two years ago: blue light from POS terminal screens dotting every fifth stall. Night markets in Lagos — once the most cash-intensive commercial spaces in the city — are quietly going cashless.</p><p>The driver isn't ideology. It's security. Night market traders told us that carrying cash home at midnight was their greatest business risk. Robbery, aggressive solicitation, and the general anxiety of moving through Lagos late at night with a day's takings was a tax on their livelihood that electronic payments eliminated overnight.</p><p>\"I used to lie about how much I made when people asked,\" says Yinka, who sells suya and pepper soup in Ajah. \"Now everything goes to my BOMPAY account and I feel safe going home. My husband doesn't know what I earn and that's the way I like it.\" (She says this with a wide smile.)</p><p>BOMPAY ePOS uptake in Lagos night market clusters has grown 340% in the past 12 months. Our field team has identified 23 distinct night market clusters in Lagos state alone that have reached tipping-point cashless adoption — meaning more than 50% of stalls accept electronic payment.</p><p>The Lagos nighttime economy is estimated at over ₦400 billion annually. It is, for the first time, becoming legible to the formal financial system.</p>","category":"Merchant Stories","tag":"Commerce","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1555993539-1732b0258235?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1555993539-1732b0258235?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2026-01-25T09:00:00Z"},
  {"blog_id":"blog_36","slug":"cable-tv-subscription-guide","title":"DStv, GOtv, or Showmax? A Nigerian's Guide to Getting the Best Entertainment Value","excerpt":"Cable TV subscriptions represent a significant monthly expense for Nigerian households. Here's how to maximise value and never miss a payment deadline again.","body":"<p>The Nigerian pay-TV landscape has expanded significantly since 2020. DStv's Premium package costs ₦24,500 per month. GOtv Max runs ₦6,200. Showmax, the streaming-only option, starts at ₦1,200. Amazon Prime Nigeria is ₦3,900. Netflix remains the most popular international option at ₦6,200 for standard definition.</p><p>For most Nigerian households, the decision is not either/or but a strategic combination. A GOtv or DStv Compact subscription (₦6,200–₦10,500) covers local news, sports (Compact only), and entertainment. A Showmax or Netflix add-on covers international content at a fraction of the cost of Premium satellite packages.</p><p>The single biggest cable TV cost for Nigerian households isn't the subscription — it's the late renewal penalty, disconnection and reconnection fees, and the emotional tax of missing important programmes. BOMPAY's automated subscription renewal (available for all major bouquets) eliminates this: your subscription renews automatically on the due date, charged from your wallet, with an SMS receipt confirming the renewal.</p><p>Set up automated cable TV renewal on BOMPAY: go to Bill Payments > Cable TV > your decoder serial number > Enable Auto-Renew. You can pause or cancel at any time with one tap. No more counting days until expiry. No more missed finals.</p>","category":"Financial Literacy","tag":"Lifestyle","author":"BOMPAY Editorial","author_role":"Editorial","thumbnail_url":"https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"5 min","published":True,"created_at":"2025-12-18T09:00:00Z"},
  {"blog_id":"blog_37","slug":"bompay-year-in-review-2025","title":"BOMPAY 2025: A Year in Numbers","excerpt":"₦450 billion processed. 12 million transactions. 150,000 Ajo groups. Here's our full-year report — the numbers, the lessons, and the plans for 2026.","body":"<p>Every year, we publish our numbers not because we're required to, but because we believe transparency is a fundamental obligation to our users. Here is 2025 in full.</p><p>Total transaction volume: ₦450 billion processed across all services — up 340% from ₦103 billion in 2024. Daily peak: ₦2.8 billion on December 24th as last-minute Christmas transfers and bill payments surged.</p><p>User growth: we ended 2025 with 518,000 active users (defined as users who transacted at least once in the past 30 days) — up from 127,000 at the end of 2024. This growth was 94% organic. We spent ₦22 million on marketing in 2025, giving us a customer acquisition cost of approximately ₦250 per new user — among the lowest in the Nigerian fintech sector.</p><p>Product performance: Ajo accounts for 34% of our daily active users. ePOS processed ₦18 billion in merchant transactions. Virtual cards were used for ₦3.4 billion in international purchases. VAS (airtime, data, electricity, cable) processed 4.2 million transactions.</p><p>Operational: we maintained 99.7% uptime across core payment services. Our average transfer success rate was 99.1% — the 0.9% of failures were entirely attributable to downstream bank/NIBSS issues, not BOMPAY infrastructure.</p><p>Looking ahead: 2026 brings BOMPAY Loans, expanded ePOS network (target: 500,000 merchants), and our first international corridor for diaspora remittances. We are grateful, energised, and focused. Thank you for 2025.</p>","category":"Company News","tag":"Milestone","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"8 min","published":True,"created_at":"2026-01-08T09:00:00Z"},
  {"blog_id":"blog_38","slug":"agent-banking-last-mile","title":"Agent Banking: How BOMPAY is Reaching the Last Mile","excerpt":"For Nigerians in underserved communities far from ATMs or bank branches, BOMPAY agents are becoming the local financial infrastructure.","body":"<p>Agent banking is one of the most impactful financial inclusion interventions in the developing world. The model is simple: authorised individuals in communities operate as banking agents, enabling their neighbours to deposit, withdraw, transfer money, and pay bills — without going to a branch or ATM.</p><p>BOMPAY's agent programme, launched in Q3 2025, has onboarded 8,500 agents across 34 Nigerian states. Agents are typically small business owners — pharmacy operators, retail shop owners, filling station attendants — who add financial services as an income supplement to their primary business.</p><p>For agents, the incentive is revenue: BOMPAY agents earn between ₦30,000 and ₦150,000 per month in commissions on transactions processed. For their communities, the value is access: an agent in Yagba East, Kogi State, provides banking services to 3,000 people who would otherwise travel 45km to the nearest ATM.</p><p>The infrastructure challenge for agent banking is liquidity management: agents need to maintain sufficient cash to handle withdrawals. BOMPAY has partnered with three logistics companies to provide daily cash replenishment for high-volume agents, and our agent app provides real-time liquidity alerts to prevent service interruptions.</p><p>Our 2026 target: 50,000 agents covering every LGA in Nigeria. The goal of financial inclusion is not to bring every Nigerian to the internet — it's to bring the internet's benefits to every Nigerian, wherever they are.</p>","category":"Company News","tag":"Inclusion","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"9 min","published":True,"created_at":"2026-02-10T09:00:00Z"},
  {"blog_id":"blog_39","slug":"betting-payments-nigeria","title":"Sports Betting and Fintech: How BOMPAY Handles Betting Transactions Responsibly","excerpt":"Nigeria has one of the most active sports betting markets in Africa. Here's how BOMPAY approaches betting payments — and the safeguards we've built.","body":"<p>Sports betting is a reality of Nigerian consumer financial behaviour. According to EFCC data, Nigerians spend over ₦500 billion annually on sports betting — with youth aged 18–35 accounting for the majority of that spend. Pretending this market doesn't exist serves no one.</p><p>BOMPAY supports betting payments through our PairGate integration, enabling users to fund betting accounts on registered platforms licensed by the Lagos State Lotteries and Gaming Authority and the National Lottery Regulatory Commission. Only platforms with valid licences are available.</p><p>We've built several safeguards into the betting payment flow. First, a confirmation step that reminds users of responsible gambling guidelines before every betting transaction. Second, optional self-exclusion controls in the wallet settings that allow users to block all betting transactions for a chosen period. Third, alerts when betting spend exceeds a user-defined monthly threshold.</p><p>We do not target betting users with promotions or discounts. We do not process peer-to-peer transfers to unlicensed betting platforms. We cooperate fully with regulatory inquiries related to betting payment flows.</p><p>Our position: adults have the right to spend their money on legal activities, including betting. Our role is to provide the infrastructure safely and responsibly, not to make that decision for them. But we can — and do — make it easy for users who want to limit their betting spend to do so.</p>","category":"Fintech Insights","tag":"Regulation","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"7 min","published":True,"created_at":"2025-10-18T09:00:00Z"},
  {"blog_id":"blog_40","slug":"qr-payments-bompay","title":"QR Payments Are Here: How BOMPAY's QR Feature Changes Street Commerce","excerpt":"Scan, confirm, done. BOMPAY QR payments enable face-to-face transactions without cash, POS hardware, or any data connection beyond a basic camera.","body":"<p>Not every merchant needs a POS terminal. Street food vendors, small kiosks, roadside artisans, and market traders often transact in amounts below ₦1,000 — amounts where POS hardware costs and merchant fees don't make financial sense. QR payments solve this.</p><p>With BOMPAY QR, any registered user can generate a static QR code that links directly to their wallet. Print it, tape it to the wall of your stall, and any customer with a BOMPAY app can scan, enter the amount, confirm, and pay — without touching POS hardware, without needing a data connection beyond the camera scan.</p><p>The merchant receives an instant SMS notification with the payment amount and customer reference. Funds are in the wallet within 3 seconds. No settlement delays, no chargebacks, no monthly rental fees for hardware.</p><p>For customers, the experience is equally simple. Open BOMPAY, tap the scan icon, point at the QR code, enter the amount, enter your transaction PIN, done. The whole process takes under 15 seconds. We tested it with market traders in Oshodi who were sceptical of any technology more complex than WhatsApp — and every single one of them preferred it to collecting cash within a week.</p><p>BOMPAY QR codes are free to generate, free to use, and require no hardware beyond a printed piece of paper. Download the app, verify your identity, and generate yours today.</p>","category":"Product Updates","tag":"Innovation","author":"Chidinma Eze","author_role":"Head of Financial Inclusion","thumbnail_url":"https://images.unsplash.com/photo-1521056787327-165eb1c9fbb6?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1521056787327-165eb1c9fbb6?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2026-02-15T09:00:00Z"},
  {"blog_id":"blog_41","slug":"bompay-paylater-beta","title":"Announcing BOMPAY PayLater: Zero-Interest 72-Hour Advance for Active Users","excerpt":"Sometimes you need ₦5,000 today and you'll have it back in three days. PayLater is our answer — no interest, no paperwork, just your transaction history.","body":"<p>PayLater is the simplest credit product we've ever built, because simplicity is the point. Sometimes people don't need a loan — they need a bridge. ₦5,000 today, repaid in 72 hours. No interest. No paperwork. Just your track record with BOMPAY.</p><p>Here's how it works: after 3 months of active BOMPAY usage (at least 10 transactions per month), you become eligible for a PayLater advance. The initial amount is ₦5,000 — enough to cover a transport emergency, an unexpected utility payment, or a gap before salary day. Your advance is in your wallet within 60 seconds. You have 72 hours to repay.</p><p>There is no interest charge on the first advance. Subsequent advances for users with perfect repayment history earn graduated limit increases — ₦10,000, ₦20,000, ₦50,000 — at the same zero-interest terms. We make no money directly from PayLater; it's a loyalty product designed to reward transacting users and expand access to emergency credit.</p><p>What happens if you don't repay within 72 hours? Your PayLater access is paused until repayment. No penalty fees. No debt collectors. No credit bureau reporting for amounts under ₦10,000. We designed this for real people in real emergencies — not to create debt traps.</p><p>PayLater beta is available now for 5,000 qualifying users. Check your eligibility under the 'Loans & Credit' section in the BOMPAY app.</p>","category":"Product Updates","tag":"Credit","author":"Adebayo Okonkwo","author_role":"CEO","thumbnail_url":"https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2026-02-08T09:00:00Z"},
  {"blog_id":"blog_42","slug":"sme-payroll-bompay-business","title":"Streamlining SME Payroll: How BOMPAY Business Saves 4 Hours Every Month","excerpt":"Manual payroll processing is expensive, error-prone, and time-consuming. Here's how BOMPAY Business automates it in three steps.","body":"<p>Payroll is the most critical financial obligation for any employer — and for most Nigerian SMEs, it's also the most manual. Business owners or accountants spend hours every month collecting bank account numbers, cross-referencing spreadsheets, initiating individual transfers, and manually verifying each transaction. The whole process is exhausting, error-prone, and completely unnecessary.</p><p>BOMPAY Business payroll works in three steps. Step one: upload a CSV or Excel file with employee names, account numbers, banks, and salary amounts. Our validator checks every account number in real time — flagging any invalid numbers before a single payment is sent. Step two: review the summary, confirm the total, enter your transaction PIN. Step three: done. Payments dispatch simultaneously to all employees, with an individual receipt automatically sent to each employee's registered phone number.</p><p>For a business paying 25 employees, this process takes under 3 minutes. The time saving compared to individual transfers is approximately 4 hours per month — time better spent on actual business growth. The error rate for batch processing (essentially zero) is dramatically lower than manual individual transfers.</p><p>BOMPAY Business payroll supports mixed banks (employees at different banks), supports part-time and contractor payments in the same batch, and provides a detailed payment confirmation report exportable as PDF for accounting records. Payroll processing starts at ₦50 per batch regardless of headcount. The month you save 4 hours, that ₦50 is the best money your business spends.</p>","category":"Product Updates","tag":"Business","author":"Emeka Nwachukwu","author_role":"VP Product","thumbnail_url":"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=srgb&fm=jpg&q=80&w=800&h=500","hero_url":"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=srgb&fm=jpg&q=80&w=1200","read_time":"6 min","published":True,"created_at":"2026-01-12T09:00:00Z"},
]

async def seed_blogs():
    """Seed blog posts if collection is empty."""
    count = await db.blogs.count_documents({})
    if count == 0:
        for post in BLOG_SEED:
            await db.blogs.insert_one({**post, "_id": post["blog_id"]})
        logger.info(f"[Blog] Seeded {len(BLOG_SEED)} posts")

@router.get("/blogs")
async def list_blogs(category: Optional[str] = None, page: int = 1, limit: int = 20):
    """Public blog listing endpoint."""
    query = {"published": True}
    if category and category != "All":
        query["category"] = category
    skip = (page - 1) * limit
    total = await db.blogs.count_documents(query)
    posts = await db.blogs.find(query, {"_id": 0, "body": 0}).sort("created_at", -1).skip(skip).limit(limit).to_list(limit)
    return {"posts": posts, "total": total, "page": page, "limit": limit}

@router.get("/blogs/{blog_id}")
async def get_blog(blog_id: str):
    """Public blog detail endpoint — accepts blog_id or slug."""
    post = await db.blogs.find_one(
        {"$or": [{"blog_id": blog_id}, {"slug": blog_id}], "published": True}, {"_id": 0}
    )
    if not post:
        raise HTTPException(404, "Blog post not found")
    return post

@router.get("/admin/blogs")
async def admin_list_blogs(request: Request, category: Optional[str] = None, published: Optional[str] = None, page: int = 1, limit: int = 30):
    """Admin: list all blog posts including unpublished."""
    user = await get_current_user(request)
    if user.get("role") != "admin":
        raise HTTPException(403, "Admin only")
    query = {}
    if category and category != "All":
        query["category"] = category
    if published == "true":
        query["published"] = True
    elif published == "false":
        query["published"] = False
    skip = (page - 1) * limit
    total = await db.blogs.count_documents(query)
    posts = await db.blogs.find(query, {"_id": 0, "body": 0}).sort("created_at", -1).skip(skip).limit(limit).to_list(limit)
    return {"posts": posts, "total": total, "page": page, "limit": limit}

@router.post("/admin/blogs")
async def create_blog(request: Request):
    """Admin: create blog post."""
    user = await get_current_user(request)
    if user.get("role") != "admin":
        raise HTTPException(403, "Admin only")
    body = await request.json()
    import re as _re
    slug = _re.sub(r"[^a-z0-9]+", "-", body.get("title", "").lower()).strip("-")
    blog_id = f"blog_{secrets.token_hex(5)}"
    doc = {
        "blog_id": blog_id, "slug": slug,
        "title": body.get("title", ""), "excerpt": body.get("excerpt", ""),
        "body": body.get("body", ""), "category": body.get("category", "Company News"),
        "tag": body.get("tag", ""), "author": body.get("author", "BOMPAY Editorial"),
        "author_role": body.get("author_role", "Editorial"),
        "thumbnail_url": body.get("thumbnail_url", ""), "hero_url": body.get("hero_url", ""),
        "read_time": body.get("read_time", "5 min"), "published": body.get("published", True),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.blogs.insert_one({**doc, "_id": blog_id})
    return doc

@router.put("/admin/blogs/{blog_id}")
async def update_blog(blog_id: str, request: Request):
    """Admin: update blog post."""
    user = await get_current_user(request)
    if user.get("role") != "admin":
        raise HTTPException(403, "Admin only")
    body = await request.json()
    body["updated_at"] = datetime.now(timezone.utc).isoformat()
    await db.blogs.update_one({"blog_id": blog_id}, {"$set": body})
    post = await db.blogs.find_one({"blog_id": blog_id}, {"_id": 0})
    return post

@router.delete("/admin/blogs/{blog_id}")
async def delete_blog(blog_id: str, request: Request):
    """Admin: delete blog post."""
    user = await get_current_user(request)
    if user.get("role") != "admin":
        raise HTTPException(403, "Admin only")
    await db.blogs.delete_one({"blog_id": blog_id})
    return {"deleted": True}


async def get_support_tickets(request: Request):
    """Return all tickets (open + resolved) for the current user — used for chat history."""
    user = await get_current_user(request)
    tickets = await db.support_tickets.find(
        {"user_id": user["_id"]}, {"_id": 0}
    ).sort("created_at", -1).to_list(50)
    return {"tickets": tickets}

